const adding = require("./add")
console.log("sum:",adding)
const subtract= require("./subtracting")
console.log("subtract:",subtract)
const multiplying= require("./mutiply")
console.log("multiply:",multiplying)
const dividing= require("./divide")
console.log("quotient:",dividing)